version: '3.4'

services:
  google-video:
    image: gdv_b:latest
    container_name: gdv_b
    restart: unless-stopped
    volumes:
      - ./config/gdv/db:/config
      - ./config/gdv/strm:/strm
      - ./config/gdv/u01:/u01
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9988:9988"
    environment:
      - STARTMODE=DEFAULT
      - DB=/config/gdrive.db
